### ISSUE TITLE
help

### ISSUE THREAD

**Issue by lordcharlx** [abhinavsuthar/Android_Spy_App_Client#2]
the server side is not as same as the one you hosted on https://hawkshaw.tk/ its rather a copy of 
https://github.com/adonespitogo/AdoBot

**Comment by abhinavsuthar** [comment]
@lordcharlx   Goto **ServerSide** directory.

**Comment by lordcharlx** [comment]
@abhinavsuthar i sent you a mail .. can you reply em please
